/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mist_pngquant_Image */

#ifndef _Included_com_mist_pngquant_Image
#define _Included_com_mist_pngquant_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mist_pngquant_Image
 * Method:    addFixedColor
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mist_pngquant_Image_addFixedColor
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_mist_pngquant_Image
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mist_pngquant_Image_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_mist_pngquant_Image
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mist_pngquant_Image_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_mist_pngquant_Image
 * Method:    liq_image_create
 * Signature: (J[BIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_mist_pngquant_Image_liq_1image_1create
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_mist_pngquant_Image
 * Method:    liq_image_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mist_pngquant_Image_liq_1image_1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
